[build]
  command = ""
  publish = "client"

# Proxy API calls from Netlify to Render backend
[[redirects]]
  from = "/api/*"
  to = "https://portfolio-cms-edne.onrender.com/api/:splat"
  status = 200
  force = true

# SPA fallback (hash routing also works, but this is safe)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
